Cart/urls.py
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='detail'),
    url(r'^add/(?P<inventory_id>\d+)/$', views.add_to_cart, name='add'),
    url(r'^remove/(?P<inventory_id>\d+)/$', views.remove_cartItem, name='remove'),
]

SurfShop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('rental.urls', namespace='index')),
    url(r'^rental/', include('rental.urls', namespace='rental')),
    url(r'^address/', include('address.urls', namespace='address')),
    url(r'^cart/', include('Cart.urls', namespace='cart')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^lecture/', include('lecture.urls', namespace='lecture')),
    url(r'^test/', include('shop.urls', namespace='shop')),
]

#if django is develop mode ...
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rental/urls.py
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^$', views.searchRentalProduct),
    url(r'^search/$', views.searchRentalProduct, name='rentalsearch'),
    url(r'^list/$', views.list_storeRentalProduct, name='rentallist'),
    url(r'^detail/(?P<inventory_id>\d+)/$', views.detail_RentalProduct, name='detail'),
    url(r'^reservation/$', views.make_reservation, name='reservation'),
    url(r'^cancel/(?P<reservation_id>\d+)/$', views.cancel_reservation, name='cancel'),
]

Cart/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

Cart/forms.py
# -*- encoding: utf-8 -*-
from django import forms

QUANTITY_CHOCIES = [(i, str(i)) for i in range(1, 12)]

class AddCartForm(forms.Form):
    #quantity = forms.TypedChoiceField(choices=QUANTITY_CHOCIES, coerce=int, label='수량')
    #quantity = forms.TypedChoiceField(label='수량')
    quantity = forms.IntegerField(widget=forms.TextInput(attrs={'class' : 'form-control'}))

Cart/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render, get_object_or_404, redirect, HttpResponse, reverse
from .cart import Cart
from rental.models import Rentalinventory
from django.views.generic import FormView
from .forms import AddCartForm
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.http import Http404
from django.template import RequestContext

#카트추가
@require_POST
def add_to_cart(request, inventory_id):
    cart = Cart(request)
    form = AddCartForm(request.POST)
    inventory = get_object_or_404(Rentalinventory, id=inventory_id)
    print form, '\n'
    if form.is_valid():
        cd = form.cleaned_data
        quantity = cd['quantity']

        #수량체크
        if inventory.rentalproduct.get_stock() >= quantity:
            cart.add(inventory=inventory, quantity=quantity)

        else:
            messages.error(request, '[Error] 주문수량이 기존수량보다 많습니다')
            refer = request.META['HTTP_REFERER']
            host = request.META['HTTP_HOST']
            url = refer.split(host)
            #수량이 일치하지 않으면 되돌아간다.
            #HTTP_HOST의 특성이 서버의 주소가 맞는지?..
            return redirect(url[1], {'messages':messages})

        return redirect('cart:detail')

def update_cart(request):
    pass

#카트 리스트(자세히)보기
def cart_detail(request):
    cart = Cart(request)

    for item in cart:
        item['update_quantity_form'] = AddCartForm(
        initial={'quantity': item['quantity']})

    return render(request, 'cart/detail.html', {'cart':cart})

def remove_cartItem(request, inventory_id):
    cart = Cart(request)
    inventory = get_object_or_404(Rentalinventory, id=inventory_id)
    cart.remove(inventory)

    return redirect('cart:detail')

templates/cart/detail.html
{% extends 'base.html' %}

{% block content %}
{% load thumbnail %}

{% for message in messages %}
  {% if message.tags == "error" %}
    <script>
      alert('{{ message }}');
    </script>
  {% endif %}
{% endfor %}

<div class="col-sm-12 col-md-10 col-md-offset-1">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>물품</th>
        <th class="text-center">가격</th>
        <th class="text-center">수량</th>
        <th class="text-center">총합</th>
        <th> </th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
      <tr>
        <td class="col-sm-8 col-md-6">
          <div class="media">
            {% thumbnail item.inventory.rentalproduct.image "150x150" crop="center" as im %}
              <a class="thumbnail pull-left" href="#"><img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"></a>
            {% endthumbnail %}
            <div class="media-body">
              <h4 class="media-heading"><a href="#">{{ item.inventory.rentalproduct.name }}</a></h4>
              <h5 class="media-heading"> by <a href="#">{{ item.inventory.store.name }}</a></h5>
            </div>
          </div></td>
          <td class="col-sm-1 col-md-1 text-center"><strong>{{ item.inventory.rentalproduct.price }}</strong></td>
          <td class="col-sm-1 col-md-1 text-center">
            <form action="{% url 'cart:add' item.inventory.id  %}" method="post">
              <div class="input-group">
              {{ item.update_quantity_form.quantity }}
              </div>
              {% csrf_token %}
              <input type="submit" value="수정" class="btn btn-secondary btn-smt">
            </form>
            해당 상품 재고 : {{ item.inventory.rentalproduct.stock }}
          </td>
          <td class="col-sm-1 col-md-1 text-center"><strong>{{ item.total_price }}</strong></td>
          <td class="col-sm-1 col-md-1">
            <a href="{% url 'cart:remove' item.inventory.id %}">
            <button type="button" class="btn btn-danger">
              <span class="glyphicon glyphicon-remove"></span> 삭제하기
            </button>
          </td>
        {% endfor %}
      </tbody>
  </table>
  <div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title">총 가격 : {{ cart.get_total_price }}</h3>
		</div>
  </div>
  <!-- 상품 검색 페이지로 이동  -->
  <a href="javascript:history.go(-1)" class="btn btn-primary">쇼핑 계속하기</a>
  <!-- <a href="{{ request.META.HTTP_REFERER }}"><button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-remove"></span> 뒤로가기</button></td> -->
  <a href="{% url 'rental:reservation' %}"><button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-remove"></span> 주문하기</button></td>
</div>
{% endblock %}