Cart/urls.py
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='detail'),
    url(r'^add/(?P<inventory_id>\d+)/$', views.add_to_cart, name='add'),
    url(r'^remove/(?P<inventory_id>\d+)/$', views.remove_cartItem, name='remove'),
]

SurfShop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('rental.urls', namespace='index')),
    url(r'^rental/', include('rental.urls', namespace='rental')),
    url(r'^address/', include('address.urls', namespace='address')),
    url(r'^cart/', include('Cart.urls', namespace='cart')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^lecture/', include('lecture.urls', namespace='lecture')),
    url(r'^test/', include('shop.urls', namespace='shop')),
]

#if django is develop mode ...
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rental/urls.py
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^$', views.searchRentalProduct),
    url(r'^search/$', views.searchRentalProduct, name='rentalsearch'),
    url(r'^list/$', views.list_storeRentalProduct, name='rentallist'),
    url(r'^detail/(?P<inventory_id>\d+)/$', views.detail_RentalProduct, name='detail'),
    url(r'^reservation/$', views.make_reservation, name='reservation'),
    url(r'^cancel/(?P<reservation_id>\d+)/$', views.cancel_reservation, name='cancel'),
]

rental/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse
from shop.models import Store
from account.models import Customer
from sorl.thumbnail import ImageField

#렌탈 상품 카테고리
class RentalCategory(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        db_table = 'RentalCategory'
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __unicode__(self):
        return self.name

    def get_absoulte_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

#렌탈 상품 모델
class RentalProduct(models.Model):
    category = models.ForeignKey(RentalCategory, related_name='products')
    name = models.CharField(max_length=45)
    description = models.TextField(blank=True)
    available = models.BooleanField(default=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    published = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    last_update = models.DateTimeField(blank=True, null=True, auto_now=True)
    image = models.ImageField(upload_to='%Y/%m/%d', blank=True)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    slug = models.SlugField(max_length=200, db_index=True)

    class Meta:
        db_table = 'RentalProduct'
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __unicode__(self):
        return self.name

    def get_absoulte_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

    def get_stock(self):
        return self.stock

    def iter_stock(self):
        dict_stock = []
        for x in range(1, self.stock + 1):
            dict_stock.append(x)
        return dict_stock

#렌탈 인벤토리 모델
#상점, 상품이랑 연결되어 있음
#검색때 유용하게 사용됨
class Rentalinventory(models.Model):
    store = models.ForeignKey(Store, related_name='store')
    rentalproduct = models.ForeignKey(RentalProduct, related_name='rentalproduct')

    class Meta:
        db_table = 'Rentalinventory'

    def __unicode__(self):
        return self.rentalproduct.name

#예약 모델
#상태코드 0 : 예약중, 1. 예약확인
class Reservation(models.Model):
    #status
    PREPARED = 0
    CONFIRMED = 1
    CANCELED = 2

    RESERVATION_STATUS = ((PREPARED, 'Prepared'),
                        (CONFIRMED, 'Confirmed'),
                        (CANCELED, 'Canceled'),)

    customer = models.ForeignKey(Customer, related_name='customer')
    inventory = models.ForeignKey(Rentalinventory, related_name='rentalinventory')
    in_date = models.DateTimeField(blank=True, null=False)
    out_date = models.DateTimeField(blank=True, null=False)
    status = models.IntegerField(null=False, choices=RESERVATION_STATUS)
    stock = models.PositiveIntegerField()

    class Meta:
        db_table = 'Reservation'
        ordering = ('in_date', 'status',) #정렬 1순위 in_date 2순위 상태

    def total_price(self):
        return self.stock * self.inventory.rentalproduct.price

    def save(self, *args, **kwargs):
        super(Reservation, self).save(*args, **kwargs) # Call the "real" save()

    def update(self, *args, **kwargs):
        print self.status, args, kwargs,'\n'

    def get_status(self):
        for i, v in self.RESERVATION_STATUS:
            if i is self.status:
                return v

Cart/forms.py
# -*- encoding: utf-8 -*-
from django import forms

QUANTITY_CHOCIES = [(i, str(i)) for i in range(1, 12)]

class AddCartForm(forms.Form):
    #quantity = forms.TypedChoiceField(choices=QUANTITY_CHOCIES, coerce=int, label='수량')
    #quantity = forms.TypedChoiceField(label='수량')
    quantity = forms.IntegerField(widget=forms.TextInput(attrs={'class' : 'form-control'}))

rental/forms.py
# -*- coding: utf-8 -*-
from django import forms

from address.models import Address, Sido, Sigungu
from django.forms import ModelChoiceField
from shop.models import Store
from address.models import Sigungu, Sido, Address
from rental.models import Rentalinventory

def queryset():
    rental = Rentalinventory.objects.all().values_list('store')
    store = Store.objects.filter(id__in=rental).values_list('address')
    address = Address.objects.filter(id__in=store).values_list('Sigungu')
    sigungu = Sigungu.objects.filter(id__in=address).values_list('sido')

    return Sido.objects.filter(id__in=sigungu)

class SigunguForm(forms.Form):
    sido = forms.ModelChoiceField(label="시도", widget=forms.Select(attrs={'class' : 'form-control'}),
    queryset= queryset())
    sigungu = forms.CharField(label="시군구", widget=forms.Select(attrs={'class' : 'form-control'}))

rental/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect, reverse, HttpResponse
from .forms import SigunguForm
from django.views.generic import FormView
from address.models import Sido, Sigungu, Address
from shop.models import Store
from rental.models import Rentalinventory, RentalProduct, Reservation
from django.core.exceptions import ObjectDoesNotExist
from Cart.forms import AddCartForm
from Cart.cart import Cart
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.utils import timezone
from account.models import Customer
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger
from django.views import generic

#렌탈 검색
def searchRentalProduct(request):
    if request.method == "GET":
        form = SigunguForm()
        return render(request, 'rental/search.html', {'form': form})

#상점 상품 리스트
def list_storeRentalProduct(request):
    form = SigunguForm(request.GET)
    cart_product_form = AddCartForm()
    cart = Cart(request)

    if form.is_valid():
        sido_name = form.cleaned_data['sido']
        sigungu_name = form.cleaned_data['sigungu']

        #예외처리
        #도중에 아무것도 없을 경우 None을 리턴
        try:
            sigungu = Sigungu.objects.filter(sido=sido_name, name=sigungu_name)
            address = Address.objects.filter(Sigungu=sigungu)
            store = Store.objects.filter(address__in=address)
            #인벤토리 검색
            inventory = Rentalinventory.objects.filter(store__in=store)
            # paginator = Paginator(inventory, 1)
            # page = request.GET.get('page')
            #
            # print page
            # try:
            #     inventory = paginator.page(page)
            # except PageNotAnInteger:
            #     inventory = paginator.page(1)
            # except EmptyPage:
            #     inventory = paginator.page(paginator.num_pages)

            for item in inventory:
                #상점의 상품 수량
                quantity = RentalProduct.objects.get(rentalproduct=item).stock
                cart_product_form = AddCartForm(initial={'quantity':  quantity })

        except ObjectDoesNotExist:
            inventory = None

        return render(request, 'rental/list.html', {'inventory': inventory,
        'cart_product_form':cart_product_form, 'address':address[0].get_name()})

#상품을 자세히 보여준다.
#인벤토리 id는 꼭 필요하며,
def detail_RentalProduct(request, inventory_id):
    form = SigunguForm()
    inventory = get_object_or_404(Rentalinventory, pk = inventory_id)

    return render(request, 'rental/detail.html', {'inventory':inventory})

#예약
#로그인 필요
@login_required(login_url='account:login')
def make_reservation(request):
    cart = Cart(request)
    user = User.objects.get(username=request.user)
    customer = Customer.objects.get(user=user)

    #예약하기 위해서는 수량을 체크해야됨
    #주문할려는 상품의 갯수가 현재 잔고보다 많은 경우 주문이 안되고 에러메세지를 출력해야됨
    for inventory in cart:
        if inventory['inventory'].rentalproduct.stock < inventory['quantity']:
            return HttpResponse('[Error] 예약수량이 기존상품보다 많습니다')

    for inventory in cart:
        stock = inventory['inventory'].rentalproduct.stock - inventory['quantity']
        inventory['inventory'].rentalproduct.stock = stock
        inventory['inventory'].rentalproduct.save()

        Reservation.objects.create(customer=customer, inventory=inventory['inventory'], in_date=timezone.now(),
        out_date=timezone.now(), status=0, stock=inventory['quantity'])

        #주문이 완료되면 장바구니에서 삭제한다.
        cart.remove(inventory['inventory'])

    return HttpResponseRedirect(reverse('account:mypage'))

@login_required(login_url='account:login')
def cancel_reservation(request, reservation_id):
    customer = Customer.objects.filter(user=request.user)
    #삭제할 예약을 얻음
    delete_reservation = Reservation.objects.get(id=reservation_id, customer=customer)
    inventory = Rentalinventory.objects.filter(id=delete_reservation.inventory.id)
    rentalproduct = RentalProduct.objects.get(id__in=inventory)
    #수량 수정
    rentalproduct.stock += delete_reservation.stock
    rentalproduct.save()
    # #예약삭제
    #delete_reservation.delete()
    #예약페이지로이동
    #템플렛에서 next, 다음 이동할 페이지를 명시해주기 때문에 return이 불필요
    return redirect(reverse('account:mypage'))

templates/rental/detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block content %}

<div class="card">
	<div class="container-fliud">
		<div class="wrapper row">
			<div class="preview col-md-6">
				<div class="preview-pic tab-content">

				  <div class="tab-pane active" id="pic-1">
            {% thumbnail inventory.rentalproduct.image "250x250" crop="center" as im %}
              <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }} class="img-responsive"">
            {% endthumbnail %}
          </div>
				</div>

			</div>
			<div class="details col-md-6">
				<h3 class="product-title">상품이름 : {{ inventory.rentalproduct.name }}</h3>
				<p class="product-description">위치 : {{ inventory.store.address }}</p>
				<div class="rating">
					<div class="stars">
						<span class="fa fa-star checked"></span>
						<span class="fa fa-star checked"></span>
						<span class="fa fa-star checked"></span>
						<span class="fa fa-star"></span>
						<span class="fa fa-star"></span>
					</div>
				</div>
				<p class="product-description">상품설명 : {{ inventory.rentalproduct.description }}</p>
				<h4 class="price">가격 : <span>{{ inventory.rentalproduct.price }}원</span></h4>
        <form action="{% url 'cart:add' inventory.id %}" method="post">
					{% csrf_token %}
					{% if inventory.rentalproduct.stock is not 0 %}
						<select id="id_quantity" name="quantity" required>
							{% for x in inventory.rentalproduct.iter_stock %}
							<option value="{{ x }}">{{ x }}</option>
							{% endfor %}
						</select>
						<input type="submit" value="장바구니"  class="btn btn-success btn-product">
					{% else %}
						품절
					{% endif %}
        </form>
			</div>
		</div>
	</div>
</div>



{% endblock %}

templates/rental/list.html
  {% extends 'base.html' %}
  {% block content %}
  {% load thumbnail %}

{% for message in messages %}
  {% if message.tags == "error" %}
    <script>
      alert('{{ message }}');
    </script>
  {% endif %}
{% endfor %}

<div>
  <h1>{{ address}}</h1>

  <div class="col-md-12">
    {% for product in inventory %}
        <div class="col-sm-6 col-md-4">
        	<div class="thumbnail" >
        		<!-- <h4 class="text-center"><span class="label label-info">{{ product.rentalproduct.name }}</span></h4> -->
            {% thumbnail product.rentalproduct.image "250x250" crop="center" as im %}
              <a href="{% url 'rental:detail' product.id %}"><img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="img-responsive"></a>
            {% endthumbnail %}

        		<div class="caption">
        				<h5>상품이름:{{ product.rentalproduct.name }}</h5>
                <label>가격:{{ product.rentalproduct.price }}원</label>
                </h5>위치:{{ product.store.address }} {{ product.store.address.other_address }}</h5>
        			<p>상품설명:</br>
              {{ product.rentalproduct.description }}
        			<div class="row">
        				<div class="col-md-6">
                  <form action="{% url 'cart:add' product.id %}" method="post">
                    {% csrf_token %}
                    {% if product.rentalproduct.stock is not 0 %}
                      <select id="id_quantity" name="quantity" required>
                        {% for x in product.rentalproduct.iter_stock %}
                        <option value="{{ x }}">{{ x }}</option>
                        {% endfor %}
                      </select>
                      <input type="submit" value="장바구니"  class="btn btn-success btn-product">
                    {% else %}
                      품절
                    {% endif %}
                  </form>
        				</div>
        			</div>
        			<p> </p>
        		</div>
        	</div>
        </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

templates/rental/search.html
{% extends 'base.html' %}

{% block content %}
	<div class="col-md-6 col-sm-6 col-md-offset-3 col-sd-offset-3">
		<h3 class="widget-title">서핑할 위치 선택</h3>
		<div class="contact-form">
			<form name="contactform" id="contactform" action="{% url 'rental:rentallist' %}" method="get">
				{{ form.as_p }}
				<input type="submit" class="mainBtn" id="submit" value="찾기">
			</form>
		</div> <!-- /.contact-form -->
	</div>

<script type="text/javascript">
    $(document).ready(function(){
        $("select#id_sido").change(function(){
            var sido_id = $(this).val();
            //비동기로 시군구 요청
            $.ajax({
                type : "GET",
                url : '/address/searchSigungu/',
                data : {'sido_id': sido_id},
                dataType: 'json',
                success:function(data){
                    //모든 옵션 삭제
                    $("select#id_sigungu").find("option").remove();

                    var list = $.parseJSON(data);
                    var listlen = list.length;
                    for(var i=0; i<listlen; i++){
                        name = list[i].name
                        //옵션 추가
                        $("select#id_sigungu").append("<option>" + name + "</option>");
                    }
                }
            });
        });
    });
</script>
{% endblock %}