Cart/urls.py
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='detail'),
    url(r'^add/(?P<inventory_id>\d+)/$', views.add_to_cart, name='add'),
    url(r'^remove/(?P<inventory_id>\d+)/$', views.remove_cartItem, name='remove'),
]

SurfShop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('rental.urls', namespace='index')),
    url(r'^rental/', include('rental.urls', namespace='rental')),
    url(r'^address/', include('address.urls', namespace='address')),
    url(r'^cart/', include('Cart.urls', namespace='cart')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^lecture/', include('lecture.urls', namespace='lecture')),
    url(r'^test/', include('shop.urls', namespace='shop')),
]

#if django is develop mode ...
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^index', views.indexView, name='index'),
    url(r'^login', views.loginView, name='login'),
    url(r'^logout', views.logoutView, name='logout'),
    url(r'^mypage', views.mypage, name='mypage'),
    url(r'^profile', views.profile, name='profile'),
    url(r'^register', views.register, name='register'),
]

lecture/urls.py
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^$', views.listtAll, name='all'),
    url(r'^list/(?P<subject>\d+)/$', views.lectureListView.as_view(), name='list'),
]

rental/urls.py
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^$', views.searchRentalProduct),
    url(r'^search/$', views.searchRentalProduct, name='rentalsearch'),
    url(r'^list/$', views.list_storeRentalProduct, name='rentallist'),
    url(r'^detail/(?P<inventory_id>\d+)/$', views.detail_RentalProduct, name='detail'),
    url(r'^reservation/$', views.make_reservation, name='reservation'),
    url(r'^cancel/(?P<reservation_id>\d+)/$', views.cancel_reservation, name='cancel'),
]

templates/base.html
{% load staticfiles %}

<html>
<head>
    <meta charset="utf-8">
    <title>LikeSurf</title>

    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">

    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <link rel="stylesheet" href="{% static 'css/normalize.min.css'%}">
    <!-- <link rel="stylesheet" href="{% static 'css/font-awesome.min.css'%}"> -->
    <link rel="stylesheet" href="{% static 'css/templatemo-misc.css'%}">
    <link rel="stylesheet" href="{% static 'css/templatemo-style.css'%}">

    <script src="{% static 'js/vendor/modernizr-2.6.2.min.js'%}"></script>
    <script src="{% static 'js/vendor/jquery-1.10.1.min.js'%}"></script>

    {% block head %}
    {% endblock %}
</head>

<body>
    <header class="site-header">
        <div class="top-header">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-sm-6">
                        <div class="top-header-left">
                            {% if user.is_authenticated %}
                              <a href="{% url 'account:mypage' %}" style="color:orange;" >{{request.user}}</a>
                              <a href="{% url 'account:logout' %}">로그아웃</a>
                              <a href="{% url 'cart:detail' %}">장바구니</a>
                              <a href="{% url 'account:mypage' %}">마이페이지</a>
                            {% else %}
                              <a href="{% url 'account:register' %}">회원가입</a>
                              <a href="{% url 'account:login' %}">로그인</a>
                            {% endif %}
                        </div> <!-- /.top-header-left -->
                    </div> <!-- /.col-md-6 -->
                </div> <!-- /.row -->
            </div> <!-- /.container -->
        </div> <!-- /.top-header -->
        <div class="main-header">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 col-sm-6 col-xs-8">
                        <div class="logo">
                            <h1><a href="{% url 'account:index' %}">LikeSurf</a></h1>
                        </div> <!-- /.logo -->
                    </div> <!-- /.col-md-4 -->

                </div> <!-- /.row -->
            </div> <!-- /.container -->
        </div> <!-- /.main-header -->
        <div class="main-nav">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-sm-7">
                        <div class="list-menu">
                            <ul>
                                <li><a href="{% url 'rental:rentalsearch'%}">렌탈</a></li>
                                <li><a href="{% url 'lecture:all' %}">강좌</a></li>
                            </ul>
                        </div> <!-- /.list-menu -->
                    </div> <!-- /.col-md-6 -->
                    <div class="col-md-6 col-sm-5">
                        <div class="notification">
                            <span> </span>
                        </div>
                    </div> <!-- /.col-md-6 -->
                </div> <!-- /.row -->
            </div> <!-- /.container -->
        </div> <!-- /.main-nav -->
    </header> <!-- /.site-header -->

    <div class="content-section">
        <div class="container">
            <div class="row">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>

</body>

</html>

templates/index.html
{% load thumbnail %}

<html>
<head>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>

<style>
.b1-box h2{
  text-align:center;
  margin:0;
  padding:0;
  width:100%;
}

html, body {
  overflow: hidden;
}

div.container {
  height: 100vh;
  width: 49%;
  display: inline-block;
  /*background-color: #ccc;*/
  overflow-y: hidden;
  padding: 0;
  /*background-image: url("http://www.surfindustries.com/shop/au/wp-content/uploads/sites/5/2013/11/type_shortboards.jpg");*/
}

.section {
  height: 100vh;
  overflow: auto;
}
/*img {
    position: absolute;
    margin: auto;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
}*/
img
{

  width: 100%;
    height: 100%;
    text-align: center;
    vertical-align: middle;
}

</style>



<body>
  <div class="container">
      <img src="http://www.surfindustries.com/shop/au/wp-content/uploads/sites/5/2013/11/type_shortboards.jpg" height="70%" width="70%">

      <h1>Side 1</h1>
      Nunc pulvinar pellentesque faucibus. Phasellus non metus eget felis ultricies dignissim. Phasellus vel viverra ligula. Morbi vestibulum congue odio, quis mattis nibh lacinia in. Ut pretium volutpat velit, eu aliquet augue pellentesque sit amet. Donec placerat mi sed finibus molestie. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Interdum et malesuada fames ac ante ipsum primis in faucibus. In in bibendum nisl. Phasellus maximus justo ac congue cursus. Suspendisse dictum risus sed tincidunt euismod. Sed feugiat semper orci, vel porttitor enim malesuada non. Nunc feugiat ante libero, sit amet congue elit semper in.

      Maecenas faucibus lacus quis nibh volutpat, vitae tincidunt sapien scelerisque. Praesent aliquam id magna ut ultrices. Suspendisse porttitor, diam a vehicula ornare, nulla mi ultrices dui, vel condimentum lectus odio quis felis. Maecenas et ligula sed nisl interdum lacinia sit amet nec tortor. Sed nisl massa, posuere in euismod in, vulputate porta ante. Integer vulputate lorem et felis viverra mollis. Vestibulum et elit eleifend, porta ante ac, interdum neque. Aenean varius eros ac leo tempor, sed tincidunt leo fermentum. Morbi a dignissim elit, id sagittis nisi.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas varius enim nec pellentesque feugiat. Mauris quis purus placerat, porttitor sapien non, rhoncus ex. Duis imperdiet purus sit amet nunc viverra pulvinar. Maecenas non risus sit amet ligula tempus aliquam at vel nunc. Fusce euismod nibh tortor, vitae mattis ligula congue vitae. Suspendisse euismod, tortor et molestie maximus, ante massa vestibulum turpis, eget interdum nibh elit vel erat. Aliquam in mi at arcu faucibus efficitur sit amet at ipsum. Etiam venenatis, nibh at molestie porta, urna ipsum congue quam, in aliquet leo velit vitae velit.


      Duis malesuada nibh nisl, nec semper ex tristique eget. Maecenas a ante neque. Cras purus eros, tristique ut laoreet tincidunt, condimentum ac mauris. Mauris in congue metus. Donec nec est nisl. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris nunc massa, blandit at dictum vitae, faucibus quis arcu. Sed auctor luctus elit id gravida. Nam eget accumsan mi.

      Aliquam ipsum nisl, feugiat at turpis ut, feugiat imperdiet nisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis non neque diam. Praesent vel velit diam. Phasellus ultricies lacus eu neque cursus aliquam. Phasellus fermentum, nisl nec sollicitudin tincidunt, nisi enim tristique felis, sit amet sagittis lectus lorem at enim. Nullam eu commodo lacus. Phasellus rutrum efficitur vestibulum.

      Nunc pulvinar pellentesque faucibus. Phasellus non metus eget felis ultricies dignissim. Phasellus vel viverra ligula. Morbi vestibulum congue odio, quis mattis nibh lacinia in. Ut pretium volutpat velit, eu aliquet augue pellentesque sit amet. Donec placerat mi sed finibus molestie. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Interdum et malesuada fames ac ante ipsum primis in faucibus. In in bibendum nisl. Phasellus maximus justo ac congue cursus. Suspendisse dictum risus sed tincidunt euismod. Sed feugiat semper orci, vel porttitor enim malesuada non. Nunc feugiat ante libero, sit amet congue elit semper in.

      Maecenas faucibus lacus quis nibh volutpat, vitae tincidunt sapien scelerisque. Praesent aliquam id magna ut ultrices. Suspendisse porttitor, diam a vehicula ornare, nulla mi ultrices dui, vel condimentum lectus odio quis felis. Maecenas et ligula sed nisl interdum lacinia sit amet nec tortor. Sed nisl massa, posuere in euismod in, vulputate porta ante. Integer vulputate lorem et felis viverra mollis. Vestibulum et elit eleifend, porta ante ac, interdum neque. Aenean varius eros ac leo tempor, sed tincidunt leo fermentum. Morbi a dignissim elit, id sagittis nisi.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas varius enim nec pellentesque feugiat. Mauris quis purus placerat, porttitor sapien non, rhoncus ex. Duis imperdiet purus sit amet nunc viverra pulvinar. Maecenas non risus sit amet ligula tempus aliquam at vel nunc. Fusce euismod nibh tortor, vitae mattis ligula congue vitae. Suspendisse euismod, tortor et molestie maximus, ante massa vestibulum turpis, eget interdum nibh elit vel erat. Aliquam in mi at arcu faucibus efficitur sit amet at ipsum. Etiam venenatis, nibh at molestie porta, urna ipsum congue quam, in aliquet leo velit vitae velit.

      Duis malesuada nibh nisl, nec semper ex tristique eget. Maecenas a ante neque. Cras purus eros, tristique ut laoreet tincidunt, condimentum ac mauris. Mauris in congue metus. Donec nec est nisl. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris nunc massa, blandit at dictum vitae, faucibus quis arcu. Sed auctor luctus elit id gravida. Nam eget accumsan mi.

      Aliquam ipsum nisl, feugiat at turpis ut, feugiat imperdiet nisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis non neque diam. Praesent vel velit diam. Phasellus ultricies lacus eu neque cursus aliquam. Phasellus fermentum, nisl nec sollicitudin tincidunt, nisi enim tristique felis, sit amet sagittis lectus lorem at enim. Nullam eu commodo lacus. Phasellus rutrum efficitur vestibulum.

      Nunc pulvinar pellentesque faucibus. Phasellus non metus eget felis ultricies dignissim. Phasellus vel viverra ligula. Morbi vestibulum congue odio, quis mattis nibh lacinia in. Ut pretium volutpat velit, eu aliquet augue pellentesque sit amet. Donec placerat mi sed finibus molestie. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Interdum et malesuada fames ac ante ipsum primis in faucibus. In in bibendum nisl. Phasellus maximus justo ac congue cursus. Suspendisse dictum risus sed tincidunt euismod. Sed feugiat semper orci, vel porttitor enim malesuada non. Nunc feugiat ante libero, sit amet congue elit semper in.

      <h1>Let's Get Started</h1>

      Maecenas faucibus lacus quis nibh volutpat, vitae tincidunt sapien scelerisque. Praesent aliquam id magna ut ultrices. Suspendisse porttitor, diam a vehicula ornare, nulla mi ultrices dui, vel condimentum lectus odio quis felis. Maecenas et ligula sed nisl interdum lacinia sit amet nec tortor. Sed nisl massa, posuere in euismod in, vulputate porta ante. Integer vulputate lorem et felis viverra mollis. Vestibulum et elit eleifend, porta ante ac, interdum neque. Aenean varius eros ac leo tempor, sed tincidunt leo fermentum. Morbi a dignissim elit, id sagittis nisi.

  </div>

  <div class="container">
    <div class="section">
      <h1>Side2</h1>

      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas varius enim nec pellentesque feugiat. Mauris quis purus placerat, porttitor sapien non, rhoncus ex. Duis imperdiet purus sit amet nunc viverra pulvinar. Maecenas non risus sit amet ligula tempus aliquam at vel nunc. Fusce euismod nibh tortor, vitae mattis ligula congue vitae. Suspendisse euismod, tortor et molestie maximus, ante massa vestibulum turpis, eget interdum nibh elit vel erat. Aliquam in mi at arcu faucibus efficitur sit amet at ipsum. Etiam venenatis, nibh at molestie porta, urna ipsum congue quam, in aliquet leo velit vitae velit.


    </div>
  </div>
</body>
</html>